export const statusColors: Record<string, string> = {
    active: "green",
    invited: "blue",
    declined: "red",
    disabled: "gray",
    inactive: "red",
    new: "blue",
    requested: "yellow",
    created: 'green',
    in_review: "gold",
    approved: "green",
    completed: "green",
    registered: "geekblue",
    unknown: "default",
    deleted: "gray",
    issued: "green",
    validating: "gold",
    in_process: "yellow",
    partially_processed: "blue",
    success: "green",
    error: "red",
    CREATED: "green",
    VALIDATING: "gold",
    IN_PROCESS: "yellow",
    PARTIALLY_PROCESSED: "blue",
    SUCCESS: "green",
    ERROR: "red",
    RECEIVED: "blue",
    APPLIED: "green",
    INTRODUCED: "yellow",
    WITHDRAWN: "blue",
    WRITTEN_OFF: "green",

    vendor_pending: "gold",
    ready_for_codes: "green",
    codes_received: "blue",

    codes_utilization_requested: "gray",
    codes_utilized: "green",
    codes_aggregated: "pink",
    rejected: "red",

    ACTIVE: "green",
    PENDING: "gold",
    EXHAUSTED: "green",
    REJECTED: "red",
    CLOSED: "gray",

    OUTSOURCED: "purple",

    READY: "green",
    exhausted: "green",
    pending: "yellow",
    ready: "blue",
    outsourcered: "yellow",

    draft: "default",
    confirmed: "geekblue",
    partially_assigned: "gold",
    assigned: "cyan",
    assigned_to_warehouse: "yellow",
    loading: "blue",
    loaded: "green",
    planned: "gold",
    handover_in_progress: "processing",
    delivering: "cyan",
    in_transit: "cyan",
    partially_delivered: "volcano",
    delivered: "green",
    issue_failed: "red",
    returning: "purple",
    returned: "gray",
    canceled: "red",
    closed: "gray",
    cancelled: "red",
    failed: "red",
    sent: "blue",
    accepted: "green",
    rejected_by_external: "red",
    None: "default",
    AwaitContractor: "gold",
    AwaitAction: "processing",
    Rejected: "red",
    Archived: "green",
    AwaitAgreement: "gold",
    AwaitSign: "processing",
    Deleted: "gray",
    AwaitThirdSide: "gold",
    ArchiveCancelRequested: "orange",
    AwaitCancelArchiveRequest: "gold",
    RejectArchiveCancelRequest: "red",
    ArchiveCanceled: "gray",
    AgreementAgreed: "green",
    AgreementReject: "red",
    SigningSigned: "green",
    SigningReject: "red",
    AwaitDecline: "gold",
    VerifiedBySystem: "green",
    AwaitResponsiblePerson: "gold",
    ResponsiblePersonAccepted: "green",
    AwaitResponsiblePersonAccepted: "gold",
    ResponsiblePersonRejected: "red",
    ResponsiblePersonTillReturned: "orange",
    ResponsiblePersonReturned: "orange",
    ReturnAccepted: "green",
    AwaitReturnAccept: "gold",
};



