export const Permissions = {
  UsersList: "users.list",
  UsersRead: "users.read",
  UsersCreate: "users.create",
  UsersUpdate: "users.update",
  UsersDelete: "users.delete",
  UsersResetPassword: "users.reset-password",
  UsersPreview: "users.preview",

  SystemEmployeesList: "system-employees.list",
  SystemEmployeesRead: "system-employees.read",
  SystemEmployeesCreate: "system-employees.create",
  SystemEmployeesUpdate: "system-employees.update",
  SystemEmployeesDelete: "system-employees.delete",

  CompanyMembershipsList: "company-memberships.list",
  CompanyMembershipsRead: "company-memberships.read",
  CompanyMembershipsCreate: "company-memberships.create",
  CompanyMembershipsUpdate: "company-memberships.update",
  CompanyMembershipsDelete: "company-memberships.delete",

  CompaniesList: "companies.list",
  CompaniesRead: "companies.read",
  CompaniesCreate: "companies.create",
  CompaniesUpdate: "companies.update",
  CompaniesDelete: "companies.delete",
  CompaniesValidateXTraceToken: "companies.validate-xtrace-token",
  CompaniesManageIntegrations: "companies.manage-integrations",
  CompaniesLegalInfoRead: "companies.legal-info.read",
  CompanyXTraceIntegrationsRead: "company-xtrace-integrations.read",
  CompanyXTraceIntegrationsValidateToken: "company-xtrace-integrations.validate-token",
  CompanyXTraceIntegrationsCreate: "company-xtrace-integrations.create",
  CompanyXTraceIntegrationsUpdate: "company-xtrace-integrations.update",
  CompanyFakturaUzIntegrationsRead: "company-faktura-uz-integrations.read",
  CompanyFakturaUzIntegrationsCreate: "company-faktura-uz-integrations.create",
  CompanyFakturaUzIntegrationsUpdate: "company-faktura-uz-integrations.update",

  ProductsList: "products.list",
  ProductsRead: "products.read",
  ProductsCreate: "products.create",
  ProductsUpdate: "products.update",
  ProductsDelete: "products.delete",

  OrdersList: "orders.list",
  OrdersRead: "orders.read",
  OrdersCreate: "orders.create",
  OrdersSynchronize: "orders.synchronize",
  OrdersCancel: "orders.cancel",
  CodesRead: "codes.read",

  ReferencesRead: "references.read",
  RolesAssign: "roles.assign",
  UploadsCreate: "uploads.create",
  UploadsDelete: "uploads.delete",

  SalesOrdersList: "sales-orders.list",
  SalesOrdersRead: "sales-orders.read",
  SalesOrdersCreate: "sales-orders.create",
  SalesOrdersUpdate: "sales-orders.update",
  SalesOrdersCancel: "sales-orders.cancel",

  DeliveryRoutesList: "delivery-routes.list",
  DeliveryRoutesRead: "delivery-routes.read",
  DeliveryRoutesCreate: "delivery-routes.create",
  DeliveryRoutesUpdate: "delivery-routes.update",
  DeliveryRoutesStartLoading: "delivery-routes.start-loading",
  DeliveryRoutesCompleteLoading: "delivery-routes.complete-loading",
  DeliveryRoutesStartTransit: "delivery-routes.start-transit",
  DeliveryRoutesStartReturn: "delivery-routes.start-return",
  DeliveryRoutesCompleteReturn: "delivery-routes.complete-return",
  DeliveryRoutesClose: "delivery-routes.close",

  DeliveryTasksList: "delivery-tasks.list",
  DeliveryTasksRead: "delivery-tasks.read",
  DeliveryTasksStartHandover: "delivery-tasks.start-handover",
  DeliveryTasksCompleteHandover: "delivery-tasks.complete-handover",

  ScanSessionsCreate: "scan-sessions.create",
  ScanSessionsComplete: "scan-sessions.complete",
  ScanSessionsScan: "scan-sessions.scan",
  ScanSessionsCancelScan: "scan-sessions.cancel-scan",

  InvoicesList: "invoices.list",
  InvoicesRead: "invoices.read",
  InvoicesCreate: "invoices.create",

  ReportsList: "reports.list",
  ReportsRead: "reports.read",
  ReportsCreateUtilization: "reports.create-utilization",
  ReportsCreateAggregation: "reports.create-aggregation",
  ReportsExportAggregation: "reports.export-aggregation",

  AuditList: "audit.list",
  AuditRead: "audit.read",
} as const;

export type Permission =
  (typeof Permissions)[keyof typeof Permissions];
