    export type AggregationDataType = {
        key: string,
        number: string,
        aggregationNumber: string,
        id: string,
        batchNumberParent: string,
        batchNumberChild: string,
        productName: string,
        aggregationQuantity: string,
        quantityPerPackage: string,
        submittedAt: string,
        status: string,
        orderIdParent: string,
        batchIdParent: string,
        childOrderId: string,
        batchOrderId: string,
    }